%% VISUALIZE A TRIAL

%% load example data
load('/Users/romanfleischmann/Library/CloudStorage/GoogleDrive-fleischmann.roman@gmail.com/My Drive/SHARE/SHARE4ANDREW/raw/subjectBAP001_Aoddball_session2_run2_8_31_10_53.mat')

%% increase signal-to-noise ratio in workspace 
% (what are all thse variables anyways)
% leftover variables are everything thats organized as "event per trial"
% helpful to get a feel for the variables

clearvars -except bufferData...
    audiocompleteTimeD...
    audiocompleteTimeP... 
    blankStartTimeD1... 
    blankStartTimeP... 
    blankStartTimeP1... 
    EndofTrial_timeD...
    EndofTrial_timeP...
    fixOffsetP...
    fixStartTimeD1...
    fixStartTimeP...
    fixStartTimeP1...
    g1_OffsetTimeD1...
    g1_OffsetTimeP...
    g1_OffsetTimeP1...
    g2_OffsetTimeP...
    g2_OnsetTimeD1...
    g2_OnsetTimeP...
    g2_OnsetTimeP1...
    inter_buttonpress...
    inter_buttonpress2...
    relaxEndTimeP...
    relaxStartTimeD1...
    relaxStartTimeP...
    relaxStartTimeP1...
    Resp1EndTimeD...
    Resp1EndTimeP...
    Resp1EndTimeP_SBP...
    Resp1StartTimeD...
    Resp1StartTimeP...
    Resp2EndTimeD... 
    Resp2EndTimeP...
    Resp2EndTimeP_SBP...
    Resp2StartTimeD...
    Resp2StartTimeP...
    SoundStartTimeD...
    SoundStartTimeD1...
    SoundStartTimeP...
    SoundStartTimeP1...
    stimulusStartTime...
    stimulusStartTimeD...
    stimulusStartTimeP

%% Visualize subset of variables w/ values within the timeframe for which there is pupil data

% "D-Variables"
varNames = {
    'audiocompleteTimeD',...
    'blankStartTimeD1',...
    'EndofTrial_timeD',...
    'fixStartTimeD1',...
    'relaxStartTimeD1',...
    'Resp1EndTimeD',...
    'Resp1StartTimeD',...
    'Resp2EndTimeD',...
    'Resp2StartTimeD',...
    'SoundStartTimeD',...
    'SoundStartTimeD1',...
    'stimulusStartTime',...
    'stimulusStartTimeD'};

nVars = numel(varNames);

% BufferData = Pupil data
% setting the range (timestamps column 1, starting from row 3)
% this is because of the -!!WEIRD ALERT!!- from the readme file
% 5 samples seems to be a safe amount to exclude
pupTimes = bufferData(5:end,1);
pupStart = min(pupTimes);
pupEnd   = max(pupTimes);

% Normalize all times to pupil data start time, because timestamps are weird
events = nan(1, nVars);
trial = 1; % default gets the first trial of a block, change here to look at another
for i = 1:nVars
    v = eval(varNames{i});   % get variable by name
    if iscell(v)
        events(i) = v{trial};    % for cell 
    else
        events(i) = v(trial);    % for num array
    end
end

events = events - pupStart; % normalize events
pupRange = [0, pupEnd - pupStart]; % normalized pupil times range

% ---- PLOTTING ----
figure; hold on;

% pupil data coverage line
plot(pupRange, [0 0], 'b-', 'LineWidth', 3);

% event points
scatter(events, zeros(1,nVars), 40, 'k', 'filled');

% labels 4 event points
for i = 1:nVars
    text(events(i), 0, varNames{i}, ...
        'Rotation', 45, 'HorizontalAlignment','left','FontSize',8);
end

xlabel('Time (s, relative to pupil data start)');
yticks([]);
title('Event Timeline (D-variables, aligned to pupil data)');
xlim(pupRange);
ylim([-1 1]);
grid on;